[0.401s] Invoking command in '/home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion': NX_CONNECTION=192.168.1.26 54739 192.168.1.53 4000 /usr/bin/cmake /home/dfolse/repos/SPIDER/SPIDER_ws/src/locomotion -DCMAKE_INSTALL_PREFIX=/home/dfolse/repos/SPIDER/SPIDER_ws/install/locomotion
[0.442s] -- Found rosidl_default_generators: 1.0.1 (/opt/ros/foxy/share/rosidl_default_generators/cmake)
[0.442s] -- Found ament_cmake_core: 0.9.12 (/opt/ros/foxy/share/ament_cmake_core/cmake)
[0.488s] -- Using PYTHON_EXECUTABLE: /usr/bin/python3
[0.897s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.903s] -- Found rosidl_adapter: 1.3.1 (/opt/ros/foxy/share/rosidl_adapter/cmake)
[1.202s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[1.293s] -- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
[1.686s] CMake Error at /opt/ros/foxy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
[1.686s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[1.686s]   locomotion --arguments-file
[1.686s]   /home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion/rosidl_adapter__arguments__locomotion.json
[1.686s]   --output-dir
[1.687s]   /home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion/rosidl_adapter/locomotion
[1.687s]   --output-file
[1.687s]   /home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion/rosidl_adapter/locomotion.idls)
[1.687s]   returned error code 1:
[1.687s] 
[1.687s]   Traceback (most recent call last):
[1.688s] 
[1.688s]     File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[1.688s]       return _run_code(code, main_globals, None,
[1.688s]     File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[1.688s]       exec(code, run_globals)
[1.688s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
[1.688s]       sys.exit(main())
[1.689s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
[1.689s]       abs_idl_file = convert_to_idl(
[1.689s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[1.689s]       return convert_msg_to_idl(
[1.689s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[1.690s]       msg = parse_message_string(package_name, input_file.stem, content)
[1.690s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 540, in parse_message_string
[1.690s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[1.690s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 387, in __init__
[1.690s]       self.base_type = BaseType(
[1.690s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 204, in __init__
[1.691s]       raise InvalidResourceName(
[1.691s] 
[1.691s]   rosidl_adapter.parser.InvalidResourceName: 'locCommands' is an invalid
[1.691s]   message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[1.691s] 
[1.691s] Call Stack (most recent call first):
[1.691s]   /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[1.692s]   CMakeLists.txt:6 (rosidl_generate_interfaces)
[1.692s] 
[1.692s] 
[1.692s] -- Configuring incomplete, errors occurred!
[1.692s] See also "/home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion/CMakeFiles/CMakeOutput.log".
[1.709s] Invoked command in '/home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion' returned '1': NX_CONNECTION=192.168.1.26 54739 192.168.1.53 4000 /usr/bin/cmake /home/dfolse/repos/SPIDER/SPIDER_ws/src/locomotion -DCMAKE_INSTALL_PREFIX=/home/dfolse/repos/SPIDER/SPIDER_ws/install/locomotion
