[0.408s] Invoking command in '/home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion': NX_CONNECTION=192.168.1.26 54739 192.168.1.53 4000 /usr/bin/cmake /home/dfolse/repos/SPIDER/SPIDER_ws/src/locomotion -DCMAKE_INSTALL_PREFIX=/home/dfolse/repos/SPIDER/SPIDER_ws/install/locomotion
[0.447s] -- Found rosidl_default_generators: 1.0.1 (/opt/ros/foxy/share/rosidl_default_generators/cmake)
[0.447s] -- Found ament_cmake_core: 0.9.12 (/opt/ros/foxy/share/ament_cmake_core/cmake)
[0.492s] -- Using PYTHON_EXECUTABLE: /usr/bin/python3
[0.904s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.926s] -- Found rosidl_adapter: 1.3.1 (/opt/ros/foxy/share/rosidl_adapter/cmake)
[1.272s] -- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "1.1.1f")  
[1.337s] -- Found FastRTPS: /opt/ros/foxy/include  
[1.512s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[1.613s] -- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
[2.011s] CMake Error at /opt/ros/foxy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
[2.012s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[2.012s]   locomotion --arguments-file
[2.012s]   /home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion/rosidl_adapter__arguments__locomotion.json
[2.012s]   --output-dir
[2.013s]   /home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion/rosidl_adapter/locomotion
[2.013s]   --output-file
[2.013s]   /home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion/rosidl_adapter/locomotion.idls)
[2.013s]   returned error code 1:
[2.014s] 
[2.014s]   Traceback (most recent call last):
[2.014s] 
[2.014s]     File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2.015s]       return _run_code(code, main_globals, None,
[2.015s]     File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[2.015s]       exec(code, run_globals)
[2.015s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
[2.016s]       sys.exit(main())
[2.016s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
[2.016s]       abs_idl_file = convert_to_idl(
[2.016s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[2.016s]       return convert_msg_to_idl(
[2.017s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[2.017s]       msg = parse_message_string(package_name, input_file.stem, content)
[2.017s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 540, in parse_message_string
[2.017s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[2.018s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 387, in __init__
[2.018s]       self.base_type = BaseType(
[2.018s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 204, in __init__
[2.018s]       raise InvalidResourceName(
[2.018s] 
[2.019s]   rosidl_adapter.parser.InvalidResourceName: 'loc_commands' is an invalid
[2.019s]   message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[2.019s] 
[2.019s] Call Stack (most recent call first):
[2.020s]   /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[2.020s]   CMakeLists.txt:6 (rosidl_generate_interfaces)
[2.020s] 
[2.020s] 
[2.020s] -- Configuring incomplete, errors occurred!
[2.021s] See also "/home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion/CMakeFiles/CMakeOutput.log".
[2.031s] Invoked command in '/home/dfolse/repos/SPIDER/SPIDER_ws/build/locomotion' returned '1': NX_CONNECTION=192.168.1.26 54739 192.168.1.53 4000 /usr/bin/cmake /home/dfolse/repos/SPIDER/SPIDER_ws/src/locomotion -DCMAKE_INSTALL_PREFIX=/home/dfolse/repos/SPIDER/SPIDER_ws/install/locomotion
